sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

php:
  - 5.6
  - 7.0

env:
  - 'DB=sqlite DEPS=""'
  - 'DB=mysql DEPS=""'
  - 'DB=pgsql DEPS=""'
  - 'DB=sqlite DEPS="--prefer-lowest"'
  - 'DB=mysql DEPS="--prefer-lowest"'
  - 'DB=pgsql DEPS="--prefer-lowest"'
  
before_install:
  - 'composer selfupdate --no-interaction'

install:
  - 'travis_retry composer update --no-interaction $DEPS'
  - 'composer info -i'
  
before_script:
  - 'if [[ "$DB" == "sqlite" ]]; then export DB_DSN="sqlite::memory:"; fi'
  - 'if [[ "$DB" == "mysql" ]]; then export DB_DSN="mysql:host=localhost;dbname=bpmn"; export DB_USERNAME="root"; mysql -e "CREATE DATABASE bpmn;" -uroot; fi'
  - 'if [[ "$DB" == "pgsql" ]]; then export DB_DSN="pgsql:host=localhost;dbname=bpmn"; export DB_USERNAME="postgres"; psql -c "CREATE DATABASE bpmn WITH ENCODING = ''UTF8'';" -U postgres; fi'

script:
  - './vendor/bin/phpunit -c "./test/phpunit.xml"'

notifications:
  email: false
